// Command apidoc renders docs/API.md from the OpenAPI spec so the endpoint
// reference can never drift from what the server embeds.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

type spec struct {
	Info  struct{ Title, Description string }
	Paths map[string]map[string]struct {
		Summary    string
		Parameters []struct {
			Name, In, Description string
			Required              bool
			Schema                map[string]any
		}
		Responses map[string]struct{ Description string }
	}
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: apidoc openapi.yaml > docs/API.md")
		os.Exit(2)
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	var s spec
	if err := yaml.Unmarshal(raw, &s); err != nil {
		panic(err)
	}
	fmt.Printf("# %s\n\n<!-- GENERATED by `make docs` from %s. Do not edit. -->\n\n%s\n\n", s.Info.Title, os.Args[1], strings.TrimSpace(s.Info.Description))
	paths := make([]string, 0, len(s.Paths))
	for p := range s.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		for method, op := range s.Paths[p] {
			fmt.Printf("## `%s %s`\n\n%s\n\n", strings.ToUpper(method), p, op.Summary)
			if len(op.Parameters) > 0 {
				fmt.Println("| Parameter | In | Type | Notes |\n|---|---|---|---|")
				for _, prm := range op.Parameters {
					notes := prm.Description
					if prm.Required {
						notes = strings.TrimSpace("required. " + notes)
					}
					if d, ok := prm.Schema["default"]; ok {
						notes = strings.TrimSpace(fmt.Sprintf("%s default `%v`", notes, d))
					}
					fmt.Printf("| `%s` | %s | %v | %s |\n", prm.Name, prm.In, prm.Schema["type"], notes)
				}
				fmt.Println()
			}
			codes := make([]string, 0, len(op.Responses))
			for c := range op.Responses {
				codes = append(codes, c)
			}
			sort.Strings(codes)
			for _, c := range codes {
				fmt.Printf("- `%s`: %s\n", c, op.Responses[c].Description)
			}
			fmt.Println()
		}
	}
	fmt.Println("## Schemas\n\nSee `components.schemas` in the spec, served live at `GET /api/v1/openapi.yaml`.")
}
